### PR TITLE
Allow for long configuration name and CAPITALISED configurations

### PR DESCRIPTION
**Pull request by plasorak**

### CODE REVIEW

**Comment by plasorak** [comment]
Hopefully this fixes: https://github.com/DUNE-DAQ/nanorc/issues/211

**Review by ArturSztuc — APPROVED** [review]
Looks good, thank you for this!

**Comment by alessandrothea** [comment]
What problem is this fixing?

**Comment by plasorak** [comment]
You can now have now `nanorc director_with_CAP session-name` with capitalised characters in the directory. Also it will only use the basename of that directory if you are doing `nanorc /nfs/home/blablab/ session-name`

**Comment by plasorak** [comment]
I'm going to merge this, this passes integ tests and all the tests that I've ran

**Pull request merged**
