### PR TITLE
start_run -> run-start & stop_run -> run-stop

### PR DESCRIPTION
**Pull request by plasorak**
Change the name of the following commands:
`start_run` -> `run-start`
`stop_run` -> `run-stop`
as it's simpler to type.

### CODE REVIEW

**Comment by wesketchum** [comment]
... do we have to do this?

**Comment by bieryAtFnal** [comment]
I very much appreciate that the current commands will be deprecated before being removed.  WIth that, that the related changes in scripts, etc. don't have to be made at exactly the same time as this change.

I'm a little confused by the naming and scope, though.  Many other commands follow a pattern of  &lt;verb&gt;_<optional noun(s)>, so I wonder if we are moving away from that with "run-start" (2 nouns?).  Is this the new pattern?  Also, there are other commands that have underscores, e.g. "enable_triggers".  Will those also be changing?

**Comment by plasorak** [comment]
For the other underscores, I guess I was a bit scared that people wouldn't be able to use the RC anymore. Now, with the deprecation warnings idea, we could just make the same changes for all of them. Let's do this here once and for all.

Here is what I think (basically no underscore anymore, only hyphens):
 - `enable_triggers` → `enable-triggers`
 - `disable_triggers` → `disable-triggers`
 - `drain_dataflow` → `drain-dataflow`
 - `stop_trigger_sources` → `stop-trigger-sources`
 - `start_shell` → `start-shell`
 - `expert_command` → `expert-command` or even `execute-expert-command`?
 - `pin_threads` → `pin-threads`
 - `change_rate` → `change-rate`
 - `change_user` → `change-user`

I'm not sure what to do about the fact that the commands are verb-noun and `run-start` is the inverse of that.

**Comment by bieryAtFnal** [comment]
Would the following translations be possible for start/stop run commands?  This would preserve the feature of having the first word be a verb...

- start_run -> start-run
- start -> prepare-for-running
- stop_run -> stop-run
- stop -> finish-run-shutdown (or finish-run-cleanup)

Independent of the names that we choose, we should make sure that this is the last time that we change these names.  I say this with the "Review and revision of appfwk complete (cmdlib,appfwk, iomanager, conf I/F, opmon I/F)" high-level task in mind.  Recall that we will be working on this high-level task through Q2 2024.  It would be silly to change these command names now and then change them again in 9 months.

**Comment by plasorak** [comment]
Could we discuss this at the next CCM meeting?

**Comment by bieryAtFnal** [comment]
Yes, of course.

**Comment by plasorak** [comment]
I'm going to assume that we want to delay discussion on this for Q2 2024.

**Pull request closed without merging**
