### PR TITLE
Resolve #10 by adding --timeout option to commands

### LINKED ISSUE #10: Add support for interactively specifying command timeout?
In tests with artificial backpressure from the DataWriter module, I've seen the Stop command sent from _nanorc_ to the Dataflow App time out.

I've worked around this by hacking the send_command function in _appctrl.py_ to have a larger value for its timeout, but it would be cool if we could interactively tell commands what timeout to use

- e.g. `stop --timeout 30`

### PR DESCRIPTION
**Pull request by eflumerf**
Also uses system timeout for `boot` instead of hard-coded 30 seconds.

### CODE REVIEW

**Comment by eflumerf** [comment]
Looks like links in the title don't work, this PR resolves #10

**Comment by eflumerf** [comment]
I split this work into two commits, one to make the boot command accept the NanoRC timeout (so `nanorc --timeout`), and the second adds a `--timeout` option to all of the commands to override the default system timeout (so `stop --timeout 60`), as Kurt requested in #10.

**Comment by plasorak** [comment]
Hi Eric, for the first commit I have no problem, this indeed seems to solve the problem. For the second, 2 things:
 - Could the default timeout in the CLI commands be `None`?
 - Can this line`cmd_timeout = timeout if timeout else self.timeout` (after the switch to None) go in `execute_command` (https://github.com/DUNE-DAQ/nanorc/blob/develop/src/nanorc/core.py#L81) since this is valid for all the commands, it should be handled as such and this reduces a lot the copy and paste.

**Comment by eflumerf** [comment]
Done and done. I'll not that when I tested `--timeout 0`, I got an exception immediately and the system went into an error state that I was unable to recover from, so 0 is still not a valid timeout value.

**Comment by plasorak** [comment]
Yeah... That's a good point about the timeout=0. There is always the option to validate the input with a callback...
```
def validate_timeout(timeout):
    if timeout<=0:
        raise click.BadParameter('Timeout needs to be > 0')
    return timeout

# and then
# for the shell option:
@click.option('--timeout', type=int, default=60, callback=validate_timeout, help='Application commands timeout') 
# for the commands:
@click.option('--timeout', type=int, default=None, callback=validate_timeout, help='stop timeout')
```
Would you mind putting that in?

**Comment by plasorak** [comment]
OK, I think I'm now happy with this. If somebody could test it it would be good.

**Comment by bieryAtFnal** [comment]
It seems that the --timeout option for the Start and Stop commands is required?  That seems a little non-backward compatible...

Also, could it be made clear in the `nanorc` command-line help whether that overall --timeout is just for boot or also becomes the default for other commands?

**Comment by plasorak** [comment]
Timeout for `start`, `stop` and `resume` didn't work, that's now fixed. The timeout you specify in the command line when starting nanorc applies to _all_ the commands, unless you specify it on an individual command:
```
nanorc --timeout 40 conf
boot # that will have a timeout of 40s
init # ditto
conf --timeout 12 # timeout of 12s
...
```
The timeout is visible deep down in the debug, straight after you issue the command, if you use `--loglevel debug`.

**Pull request merged**
