### PR TITLE
bug fix for expert command, include and exclude

### PR DESCRIPTION
**Pull request by LJoyL**
PR for issue #218

### CODE REVIEW

**Comment by plasorak** [comment]
Do include/exclude require the same treatment too?

**Comment by LJoyL** [comment]
I supposed it was interesting if it end up being implemented in an integration test in the future. I only need the expert command in my case so we can revert for include and exclude if it is not required.

**Comment by plasorak** [comment]
Hi Leo, do you have an example of an expert command json?

**Comment by plasorak** [comment]
ok, I found it:
```json
{
    "id": "record",
    "entry_state": "ANY", # can be omitted
    "exit_state": "ANY", # can be omitted
    "data": {} # can be omitted
}
```

**Pull request merged**
