### PR TITLE
Plasorak/web and rest nanorc

### LINKED ISSUE #71: Run Control GUI
I'm creating this Issue (with Zbynek's permission) as a placeholder for the work that he is doing on the RC GUI.  The purpose of the placeholder is to allow us to keep track of which release the work is planned for, etc.

### PR DESCRIPTION
**Pull request by plasorak**
Development towards https://github.com/DUNE-DAQ/nanorc/issues/71

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
With the fix from Pierre for the problem that I saw when trying to 'pip install' this branch of `nanorc`,  I ran a couple of tests. 
In the first one, I forgot to download the `frames.bin` file.  The RC GUI correctly reported an error on the Conf transition, but I had to go to the logfiles to learn the error.
In the second one, I deliberately omitted the setting of a run number before I clicked the Start button.  In this case, the server output the following error

- `invalid literal for int() with base 10: ''`

and the server seemed to become unresponsive after that.

**Comment by plasorak** [comment]
Thanks Kurt, that's very helpful

**Comment by cvzbynek** [comment]
Thank you Kurt for your testing effort. Runnumber issue should be fixed now

**Comment by plasorak** [comment]
OK, so, now the basic idea is that one can do `nanorc --web config_dir`.

**Comment by bieryAtFnal** [comment]
I've run integration tests with the branch, and all of those looked good.

In addition, I've run a couple of tests with "nanorc --web <config>".  The only odd thing there is that I can't find the output HDF5 file(s).  I wonder if the start command is silently using the --disable-data-storage argument to "start"...

**Pull request merged**
