### PR TITLE
kill services in a try/catch block. Test APP_PORT before startng apps

### PR DESCRIPTION
**Pull request by plasorak**

### CODE REVIEW

**Review by bieryAtFnal — APPROVED** [review]
These changes look fine to me.  However, it was Ron Rechenmacher who is more familiar with problems starting and killing ConnSvc instances, so it may be useful to ask for Ron's review also.  My tests were to simply verify that existing functionality continued to work.  

And, I'm delighted to report that when the "start_connectivity_service" daqconf config parameter is set to false, the connectivity service port does not get a port offset added to it.  This allows DAQ sessions that do not start the ConnSvc to easily specify the ConnSvc port to use.

**Comment by ron003** [comment]
I tried running with both nanorc  plasorak/connectivity-server-fixes and
daqconf plasorak/port-connection-svc -- with this, it seems the default connectivity serv port defaults to 15000. I had an old conn serv running on 5000 and there seemed to be a conflict. I ran the nanorc (non-integ test) and the system failed fairly gracefully (no statck trace).
I would like to do more testing.

**Comment by jcfreeman2** [comment]
Two additional comments
1) Discussed at this morning's release meeting: while port 15000 is an improvement over 5000, we could reduce the likelihood of port conflict on a system if we _didn't_ make the port number a nice round number. Something more random, e.g. 15489, would generally be safer.
2) It might be nice in the nanorc documentation to describe how to fix a port clog (i.e. `netstat -tulpn | grep <port number>` to get the PID, then `kill <PID>`. This would at least work in the event that the user had caused the port clog in the first place, which is what happens, e.g., if one tries running on the `np04` cluster without first doing `source ~np04daq/bin/web_proxy.sh -u`, and then hits `Ctrl-c` to escape the hang)

**Comment by jcfreeman2** [comment]
In fact, concerning (2) Kurt pointed out that in the daqconf Wiki people are instructed to add
```
[http]
  proxy = http://np04-web-proxy.cern.ch:3128
  sslVerify = false
```
to their `.gitconfig` file so they don't have to source `~np04daq/bin/web_proxy.sh -u` each time they login; could we also update the https://dune-daq-sw.readthedocs.io/en/latest/packages/nanorc/FAQ/#nanorc-cant-start-the-response-listener-what-do-i-do section of the nanorc documentation to mention this?

**Review by ron003 — APPROVED** [review]
Runs fine - starts and stops conn serv on appropriate port

**Pull request merged**
