### PR TITLE
FAQ

### PR DESCRIPTION
**Pull request by plasorak**

### CODE REVIEW

**Comment by plasorak** [comment]
Fixes https://github.com/DUNE-DAQ/nanorc/issues/129

**Review by wesketchum — APPROVED** [review]
Thanks for updating!

**Comment by jcfreeman2** [comment]
@plasorak @wesketchum Since this is a change to documentation, we should (also) merge this into `develop`; that way it'll be picked up in https://dune-daq-sw.readthedocs.io/en/latest/packages/nanorc/

**Comment by plasorak** [comment]
Indeed, I'll merge the patch branch in develop when all the PRs are in.

**Pull request merged**
