### PR TITLE
fixes to the logbook configuration (doesn't actually use the ~/.nanor…

### PR DESCRIPTION
**Pull request by plasorak**
…c.json?!?!)

### CODE REVIEW

**Review by TiagoTAlves — COMMENTED** [review]
When testing this I got an error saying that couldn't find np04_hd in dotnanorc:

```
(dbt) [np04daq@np04-srv-024 dunedaq-NFD_PROD4_240328-dev]$ rc04 global_configs/np04_WIB_100mHz.json titavare
Launching 'nano04rc --partition-number 5 --timeout 120 global_configs/np04_WIB_100mHz.json titavare np04hddev'
╭──────────────────────────────────────────────────────────────────────────╮
│                             Shonky Nano04RC                              │
│  This is an admittedly shonky nano RC to control DUNE-DAQ applications.  │
│    Give it a command and it will do your biddings,                       │
│    but trust it and it will betray you!                                  │
│  Use it with care, user!                                                 │
╰──────────────────────────────────────────────────────────────────────────╯
Loading /nfs/home/np04daq/.nanorc.json
[19:33:37] INFO     RunDB socket http://np04-srv-017.cern.ch:30016                                                                                                                                                      __main_np04__.py:102
           INFO     RunRegistryDB socket http://np04-srv-017.cern.ch:30015                                                                                                                                              __main_np04__.py:103
           ERROR    Can't find apparatus 'np04_hd' in dotnanorc, reverting to file logbook!                                                                                                                             __main_np04__.py:118
           INFO     nano-conf-svc Flask lives on PID: 122282                                                                                                                                                                     utils.py:57
FSM available states: ['none', 'booted', 'initial', 'configured', 'ready', 'running', 'paused', 'dataflow_drained', 'trigger_sources_stopped', 'error']
FSM available transitions: {'enable_triggers', 'stop', 'terminate', 'boot', 'start', 'stop_trigger_sources', 'abort', 'conf', 'drain_dataflow', 'scrap', 'disable_triggers'}
Extra commands are []
[19:33:53] INFO     Using filelogbook                                                                                                                                                                                            core.py:112
Running on the apparatus np04_hd:
╭─────────────────╮
│ np04_hd         │
│ ├── np04_wib    │
│ ├── np04_hermes │
│ └── np04_daq    │
╰─────────────────╯
titavare@np04rc> exit
[19:34:37] INFO     nano-conf-svc-flaskmanager terminated
```  

Maybe we should consider reviewing

**Comment by plasorak** [comment]
Do you have a np04_hd in the `~/.nanorc.json`?

**Comment by wesketchum** [comment]
I got the same error when I tried (thanks @TiagoTAlves for reporting it here). 

Here's the `.nanorc.json` file. So, there is a `np04_hd` in the `elisa_configuration` block, but I'm not sure if that's the right level that the code is expecting? Haven't have time to try to follow that through.

```
[wketchum@np04-srv-024 ~]$ cat ~np04daq/.nanorc.json
{
    "cern": {
        "elisa_configuration":{
            "np02_coldbox": {
                "connection": "https://np-vd-coldbox-elog.app.cern.ch/elisa/api/np-vd-coldbox-elog/",
                "website": "https://np-vd-coldbox-elog.app.cern.ch/",
                "attributes": {
                    "start": {
                        "type": {
                            "set_on_reply": false,
                            "set_on_new_thread": true,
                            "value":"Automatic"
                        },
                        "Automatic_Message_Type": {
                            "set_on_reply": true,
                            "set_on_new_thread": true,
                            "value":"SoR"
                        }
                    },
                    "stop": {
                        "type": {
                            "set_on_reply": false,
                            "set_on_new_thread": true,
                            "value":"Automatic"
                        },
                        "Automatic_Message_Type": {
                            "set_on_reply": true,
                            "set_on_new_thread": true,
                            "value":"EoR"
                        }
                    },
                    "message": {
                        "type": {
                            "set_on_reply": false,
                            "set_on_new_thread": true,
                            "value":"Automatic"
                        },
                        "Automatic_Message_Type": {
                            "set_on_reply": true,
                            "set_on_new_thread": true,
                            "value":"Alarm"
                        }
                    }
                }
            },
            "np02_pds": {
                "connection": "https://np-vd-coldbox-elog.app.cern.ch/elisa/api/np-vd-coldbox-elog/",
                "website": "https://np-vd-coldbox-elog.app.cern.ch/",
                "attributes": {
                    "start": {
                        "type": {
                            "set_on_reply": false,
                            "set_on_new_thread": true,
                            "value":"Automatic"
                        },
                        "Automatic_Message_Type": {
                            "set_on_reply": true,
                            "set_on_new_thread": true,
                            "value":"SoR"
                        }
                    },
                    "stop": {
                        "type": {
                            "set_on_reply": false,
                            "set_on_new_thread": true,
                            "value":"Automatic"
                        },
                        "Automatic_Message_Type": {
                            "set_on_reply": true,
                            "set_on_new_thread": true,
                            "value":"EoR"
                        }
                    },
                    "message": {
                        "type": {
                            "set_on_reply": false,
                            "set_on_new_thread": true,
                            "value":"Automatic"
                        },
                        "Automatic_Message_Type": {
                            "set_on_reply": true,
                            "set_on_new_thread": true,
                            "value":"Alarm"
                        }
                    }
                }
            },
            "np04_coldbox": {
                "connection": "https://pdsp-elog.app.cern.ch/elisa/api/ProtoDUNE-SP/",
                "website": "https://pdsp-elog.app.cern.ch",
                "attributes": {
                    "start": {
                        "type": {
                            "set_on_reply": false,
                            "set_on_new_thread": true,
                            "value":"RunControl Message"
                        },
                        "RunControl_MessageType": {
                            "set_on_reply": true,
                            "set_on_new_thread": true,
                            "value":"status"
                        }
                    },
                    "stop": {
                        "type": {
                            "set_on_reply": false,
                            "set_on_new_thread": true,
                            "value":"RunControl Message"
                        },
                        "RunControl_MessageType": {
                            "set_on_reply": true,
                            "set_on_new_thread": true,
                            "value":"status"
                        }
                    },
                    "message": {
                        "type": {
                            "set_on_reply": false,
                            "set_on_new_thread": true,
                            "value":"RunControl Message"
                        },
                        "RunControl_MessageType": {
                            "set_on_reply": true,
                            "set_on_new_thread": true,
                            "value":"status"
                        }
                    }
                }
            },
            "np04_hd": {
                "connection": "https://pdsp-elog.app.cern.ch/elisa/api/ProtoDUNE-SP/",
                "website": "https://pdsp-elog.app.cern.ch",
                "attributes": {
                    "start": {
                        "type": {
                            "set_on_reply": false,
                            "set_on_new_thread": true,
                            "value":"RunControl Message"
                        },
                        "RunControl_MessageType": {
                            "set_on_reply": true,
                            "set_on_new_thread": true,
                            "value":"status"
                        }
                    },
                    "stop": {
                        "type": {
                            "set_on_reply": false,
                            "set_on_new_thread": true,
                            "value":"RunControl Message"
                        },
                        "RunControl_MessageType": {
                            "set_on_reply": true,
                            "set_on_new_thread": true,
                            "value":"status"
                        }
                    },
                    "message": {
                        "type": {
                            "set_on_reply": false,
                            "set_on_new_thread": true,
                            "value":"RunControl Message"
                        },
                        "RunControl_MessageType": {
                            "set_on_reply": true,
                            "set_on_new_thread": true,
                            "value":"status"
                        }
                    }
                }
            }
        },
        "run_registry_configuration":{
            "socket": "http://np04-srv-017.cern.ch:30015"
        },
        "run_number_configuration":{
            "socket": "http://np04-srv-017.cern.ch:30016"
        },
        "authentication": {
            "run_registry": {
                "user": "fooUsr",
                "password": "barPass",
                "type": "simple"
            },
            "run_number": {
                "user": "fooUsr",
                "password": "barPass",
                "type": "simple"
            },
            "elisa": {
                "user": "rcpd",
                "type": "service-account",
                "realm": "CERN.CH"
            }
        }
    }
}
```

**Comment by plasorak** [comment]
@wesketchum, @TiagoTAlves I've corrected the logic.

**Comment by bieryAtFnal** [comment]
Changed the target merge branch to `prep-release/fddaq-v4.4.0` now that the first release candidate has been built.

**Review by TiagoTAlves — APPROVED** [review]

**Pull request merged**
