### PR TITLE
fix env variables

### PR DESCRIPTION
**Pull request by plasorak**

### CODE REVIEW

**Review by eflumerf — APPROVED** [review]
LGTM

**Comment by dingp** [comment]
@plasorak What are in `env_var` that needed in  addition to the the rte script? Just the additional envs used in `conf_utils.py`? If so, I can add them into the rte script.

**Comment by plasorak** [comment]
Well, I added everything, but the thing that triggered the problem was run control specific, it was the name of the partition.

**Comment by plasorak** [comment]
but after looking at it in more details, there were also all these:
```
    "env": {
        "DUNEDAQ_ERS_DEBUG_LEVEL": "getenv_ifset",
        "DUNEDAQ_ERS_ERROR": "erstrace,throttle,lstdout,erskafka(monkafka.cern.ch:30092)",
        "DUNEDAQ_ERS_FATAL": "erstrace,lstdout,erskafka(monkafka.cern.ch:30092)",
        "DUNEDAQ_ERS_INFO": "erstrace,throttle,lstdout,erskafka(monkafka.cern.ch:30092)",
        "DUNEDAQ_ERS_STREAM_LIBS": "erskafka",
        "DUNEDAQ_ERS_VERBOSITY_LEVEL": "getenv:1",
        "DUNEDAQ_ERS_WARNING": "erstrace,throttle,lstdout,erskafka(monkafka.cern.ch:30092)"
    },
```
Hence I added everything

**Comment by dingp** [comment]
Sounds good! Thanks for the explanation!

**Pull request merged**
